### ISSUE TITLE
Multi-sections support

### ISSUE THREAD

**Issue by aelam** [bannzai/SpreadsheetView#119]
## Expected Behavior

Do you have  a plan to make it multi-sectioned? it would be awesome 

## Specifications

  - Xcode version: ?
  - iOS version: ?
  - Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
@aelam It's unclear for me. Could you explain in detail? What multi-sections looks like? Do you know any other spreadsheet apps/services that have such features?

**Comment by aelam** [comment]
Hi Kishikawa San,

It looks like this 



发自我的 iPhone

**Comment by kishikawakatsumi** [comment]
@aelam Maybe you forgot to attach an image.

**Comment by aelam** [comment]
![eb8089adbba6a5d32820333c5a638e18](https://user-images.githubusercontent.com/232337/29320384-910b16b0-8209-11e7-9b3c-c833e51dd8a4.jpg)

**Comment by kishikawakatsumi** [comment]
@aelam Thank you. I don't have a plan to add such functionality at the moment. Because `SpreadsheetView` has no concept of the section, adding it makes the API too complicated. I will consider supporting it if many other people who want such feature.

The view you shared can be made easier using `UITableView` or `UICollectionView` than `SpreadsheetView`. I recommend you using `UITableView` or `UICollectionView` instead.

Thank you for your suggestion! If you have further questions, please feel free to reopen the issue and comment it.

**Comment by brendand** [comment]
I would vote for section headers as well. Just like in a UITableView sections, but with multiple columns.

In the Mac version of my app I have frozen columns and sections in the table grid control. It would be great to be able to offer these things in the iOS version too. Right now I'm using MDSpreadView for a grid control on iOS, but it doesn't support frozen columns like your control does.

<img width="956" alt="screen shot 2018-11-22 at 6 52 54 pm" src="https://user-images.githubusercontent.com/586075/48926094-fd273180-ee87-11e8-89df-2ffd9fbebd99.png">
