### ISSUE TITLE
Sorting by value not by text

### ISSUE THREAD

**Issue by jst04004** [bannzai/SpreadsheetView#160]
## Expected Behavior
Thank you for your work. I am new to Swift and this has helped a lot. I am following the example of the class example and am modifying some things. I have a column that I would like to display numerical values. Currently they are stored as strings. When I sort, it does so assuming it is text. That is it will sort [1, 5, 4, 10,20,] as [1, 10, 20,4,  5] based on the first digits or values in the string. So the expected / desired result would be [1,4,5,10,20].

Would you know a good way to work around this?

## Actual Behavior
 Sorts as [1, 10, 20,4,  5]

## Steps to Reproduce the Problem

  1. Change one column of data to numbers
  1. sort on column
  

## Specifications

  - Xcode version: 9

**Comment by kishikawakatsumi** [comment]
@jst04004 There are several ways, one of which is to use `compare(_:options:range:locale:)` method rather than the operator comparison. In the `compare(_:options:range:locale:)` method, you can specify comparison options, then if you specify the `.numeric` option there, the comparison results are in numerical order instead of dictionary order.

```
func spreadsheetView(_ spreadsheetView: SpreadsheetView, didSelectItemAt indexPath: IndexPath) {
    ...

        data.sort {
            let ascending = $0[sortedColumn.column].compare($1[sortedColumn.column], options: .numeric) == .orderedAscending
            return sortedColumn.sorting == .ascending ? ascending : !ascending
        }
    ...
}
```

**Comment by jst04004** [comment]
Thank you very much! I will try something like this.
