### ISSUE TITLE
Colour attributes of a cell are transferred to wrong cells when scrolling

### ISSUE THREAD

**Issue by jpopham** [bannzai/SpreadsheetView#41]
If the same subclass of Cell is used for all four areas of a SpreadsheetView with a fixed row and column, then changes to colour attributes in spreadsheetView cellForItemAt are scattered over incorrect cells when the spreadsheet view if scrolled:
[Example](https://github.com/kishikawakatsumi/SpreadsheetView/files/1011804/testSS2.zip).  The wrong colour attributes are cleared by a reloadData.
This does not occur if all four areas (ie top left - frozen row and column, top - frozen row, left - frozen column and non-frozen rows/columns) are associated with  different subclasses of Cell:
[Example 2](https://github.com/kishikawakatsumi/SpreadsheetView/files/1011806/testSS3.zip)
These examples are using the reloading branch.

**Comment by kishikawakatsumi** [comment]
@jpopham It is an expected behavior. `SpreadsheetView` reuses `Cell` for performance as same as `UITableView` and `UICollectionView`. You should reset custom attributes before reusing if you set same reuse identifier to all cells. 

```
if indexPath.column == 0 {
    if indexPath.row == 0 {
        cell.label.text = ""
    } else {
        cell.label.text = "\(indexPath.row)"
        cell.color = UIColor.blue
        ...
    }
} else {
    if indexPath.row == 0 {
        cell.label.text = "\(headers[indexPath.column - 1])"
        cell.color = UIColor.red
        ...
    } else {
        cell.label.text = "\(rows[indexPath.row][indexPath.column - 1])"
    }
}
```

^ You change cell's background color at column and row header (`indexPath.column == 0` and `if indexPath.row == 0`). But you do not set default background color in `else` clause. That's why reused cell kept its background color. You should also set a color in `else` clause, or you can use `prepareForReuse()` method to reset cell's state.

**Comment by jpopham** [comment]
Yes of course, my mistake. Sorry about that
